### ISSUE TITLE
CreateMarkdownHelp fails if module is not imported

### ISSUE THREAD

**Issue by TsekNet** [techthoughts2/Catesta#26]
The `CreateMarkdownHelp` task fails (technically platyPS fails) when trying to generate Markdown help if the module being tested is not already installed locally.

I'll leave it up to you whether this is a critical issue or not, but this was a blocker for me getting started using Catesta. Not importing the module as to not interfere with local modules may be WAI, but I did not see this in the FAQ/documentation. PowerShell module scopes may help resolve this.

### Expected Behavior

platyPS generates the markdown docs without issue. This requires (at least in its current implementation) that the module is first installed.

### Current Behavior

The module build fails with the error below:

```powershell
Task /./CreateHelpStart/CreateMarkdownHelp : Build markdown help files for module and fail if help information is missing
At D:\projects\testmodule\testmodule\src\test.build.ps1:276
Manifest File: D:\projects\testmodule\testmodule\src\test\test.psd1
Manifest Version: 0.1.0
           Generating markdown files...
ERROR: Module test is not imported in the session. Run 'Import-Module test'.
At C:\Program Files\WindowsPowerShell\Modules\platyPS\0.12.0\platyPS.psm1:261 char:25
+ ...             throw "Module $_ is not imported in the session. Run 'Imp ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At D:\projects\testmodule\testmodule\src\test.build.ps1:276 char:1
+ Add-BuildTask CreateMarkdownHelp -After CreateHelpStart {
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At D:\projects\testmodule\testmodule\src\test.build.ps1:267 char:1
+ Add-BuildTask CreateHelpStart {
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At D:\projects\testmodule\testmodule\src\test.build.ps1:41 char:1
+ Add-BuildTask -Name . -Jobs $str
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Build FAILED. 8 tasks, 1 errors, 0 warnings 00:00:03.0509986
Module test is not imported in the session. Run 'Import-Module test'.
At C:\Program Files\WindowsPowerShell\Modules\platyPS\0.12.0\platyPS.psm1:261 char:25
+ ...             throw "Module $_ is not imported in the session. Run 'Imp ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Module test is ...t-Module test'.:String) [], RuntimeException
    + FullyQualifiedErrorId : Module test is not imported in the session. Run 'Import-Module test'.
```

### Possible Solution

Add the following to the `CreateHelpStart` task, you'll likely want to use `-Force` here as to reinstall the module that was just built.

```powershell
Write-Build Gray "           Importing $ModuleName v$ModuleVersion ..."
Import-Module -Name $script:ModuleManifestFile -Global -Force -PassThru -ErrorAction Stop
Write-Build Gray "           ...$ModuleName imported successfully."
```

You may also want to add removing this module at the beginning of every run's cleanup.

### Steps to Reproduce

1. Install Catesta
2. Execute `Invoke-Build` from the `src` directory
3. The build should fail with the error described above

### Context (Environment)

* Operating System and version as reported by `$PSVersionTable.OS`:
* PowerShell versions as reported by `$PSVersionTable.PSEdition`:

OS: win10-2004 (`$PSVersionTable.OS` does not exist on PowerShell 5.1)

```powershell
 $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by TsekNet** [comment]
Adding that I found a good example of this in the Plaster psake file template [here](https://github.com/PowerShellOrg/Plaster/blob/master/examples/NewModule/build.psake.ps1#L244).

**Comment by techthoughts2** [comment]
Ack. This is definitely an undesired bug that I will work to address. Thanks for submitting it.
