### ISSUE TITLE
Remove Export-ModuleMember from Catesta.psm1

### ISSUE THREAD

**Issue by TsekNet** [techthoughts2/Catesta#37]
### Expected Behavior

Catesta already exports module members via the module manifest, there is no need to add Export-ModuleMember to the module as well. By default, creating a new module will fail due to the PSScriptAnalyzer rule that does not allow for wildcard exports in the module manifest, so this field must be modified for all modules to build successfully.

### Current Behavior

Catesta executes `Export-ModuleMember -Function $public.Basename` as part of every time the module is imported ([link](https://github.com/techthoughts2/Catesta/blob/70f6c75ffad67fadbf4b841766fcadb381398dd4/src/Catesta/Catesta.psm1#L34)).

### Possible Solution

Remove `Export-ModuleMember` from the module itself, and leave this to the manifest. I will submit a PR for this.

### Steps to Reproduce

1. Build any module
2.
3.
4.

### Context (Environment)

* Operating System and version as reported by `$PSVersionTable.OS`:
* PowerShell versions as reported by `$PSVersionTable.PSEdition`:

### Detailed Description

I'll note that this is not a high priority issue, this technically works, just the effort is duplicated. For context, this suggestion was taken from this [Reddit](https://www.reddit.com/r/PowerShell/comments/j1y94s/published_my_first_module_to_the_powershell/g72wwdp/) post.

**Comment by techthoughts2** [comment]
As mentioned [here](https://old.reddit.com/r/PowerShell/comments/j1y94s/published_my_first_module_to_the_powershell/g79pm6c/) this is done on purpose.

There are local development scenarios where the psm1 may be called directly.

The documentation for **[Export-ModuleMember](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/export-modulemember?view=powershell-7)** covers this in more detail:

>If a script module does not include an Export-ModuleMember command, the functions and aliases in the script module are exported, but the variables are not. When a script module includes Export-ModuleMember commands, only the members specified in the Export-ModuleMember commands are exported. You can also use Export-ModuleMember to suppress or export members that the script module imports from other modules.
An Export-ModuleMember command is optional, but it is a best practice. Even if the command confirms the default values, it demonstrates the intention of the module author.

Feel free to reopen this if you have additional concerns.
