### ISSUE TITLE
Upgrade Pester and some of the dependencies

### ISSUE THREAD

**Issue by asears** [techthoughts2/Catesta#45]
### Description
Pester 5 is out.   Current templates scaffold with Pester 4.

### Describe the solution you'd like
Upgrade the dependencies and a few bits of test scripts to Pester 5?

Some of the other dependencies may also use an upgrade bump.  (platyPS, InvokeBuild)
PlatyPS preview may fix the open issue.
https://github.com/PowerShell/platyPS/blob/v2/src/Model/Constants.cs

**Comment by techthoughts2** [comment]
Pester 5 capabilities have been added in the latest release.

I also bumped a few of the dependencies.

I evaluated platyPS ``` 2.0.0 preview1``` and it is much improved but still has several issues. It looks like several of them are in active triage. So, for now, I'm holding off as ```0.12.0``` continues to generate help without issue.

I will continue to evaluate the platyPS 2.0.0 release as it tracks towards GA.
