### ISSUE TITLE
Casing issue related to folder Editor which causes undesired behavior on certain OS's

### ISSUE THREAD

**Issue by techthoughts2** [techthoughts2/Catesta#59]
@dganev-cb filed PR #58 highlight an issue with the Paths regarding the case of the folder `Editor`

### Expected Behavior
Catesta should operate as expected on all supported OS's.

### Current Behavior
Incorrect casing seems to be causing an issue on a Linux based OS when running Catesta.

### Possible Solution
Correct casing related to Editor.
Potentially explore other casing issues as well.

### Steps to Reproduce
See screenshot in #58

### Context (Environment)
Unknown. @dganev-cb can you prove your environment details?

* Operating System and version as reported by `$PSVersionTable.OS`:
* PowerShell versions as reported by `$PSVersionTable.PSEdition`:

### Detailed Description
Explore casing issues that may be causing an issue with Catesta on Linux based operating systems. Test on a variety of Linux based hosts and correct the Editor casing as well as explore other potential casing issues.

**Comment by syrull** [comment]
@techthoughts2 I cannot use the specific system at the moment however the OS was `Ubuntu Server 22.04` and the Powershell Edition was `Core`
