### ISSUE TITLE
Support namespaced module

### ISSUE THREAD

**Issue by OnceUponALoop** [techthoughts2/Catesta#73]
### Description

Catesta does not support a namespaced module name (ex. `MyModule.Utils`)

### Describe the solution you'd like

Simply support module names with a dot/period.

### Additional context

At a glance, it seems a simple change to `Module.build.ps1` `$ModuleName` parsing will address this.

**From**
`$ModuleName = (Split-Path -Path $BuildFile -Leaf).Split('.')[0]` 
and `$script:ModuleName = (Split-Path -Path $BuildFile -Leaf).Split('.')[0]` 

**To**
`$ModuleName = ((Get-Item $BuildFile).BaseName) -replace ".build$"` 
and `$script:ModuleName =  ((Get-Item $BuildFile).BaseName) -replace ".build$"`

**Comment by techthoughts2** [comment]
Great suggestion.
Will be included in the next release.

**Comment by OnceUponALoop** [comment]
I'm sorry I didn't update sooner, one other place where I found manual intervention was required was the vscode `tasks.json` - I couldn't find a good solution for it though, I ended up manually editing it (shrug)

I had to manually edit `workspaceFolderBasename` through find and replace

**Comment by techthoughts2** [comment]
@OnceUponALoop

I tested and the `tasks.json` tasks are working as expected.
`workspaceFolderBasename` does expect that the base folder name to be the module name.

Can you open a new issue with the details of the error you are getting, or a suggestion to improve if its not clear?
