### ISSUE TITLE
Catesta Feature request - Support for classes

### ISSUE THREAD

**Issue by dsolodow** [techthoughts2/Catesta#89]
### Description
We have public and private folders for those functions; having a way to handle classes would be helpful.

### Describe the solution you'd like
Add a Classes folder to the scaffolding (perhaps behind a parameter?) and update the build tasks accordingly

### Describe any alternatives you've considered
Still researching.

**Comment by techthoughts2** [comment]
I'm open to the idea of adding a Classes folder, but I need a bit more detail to understand how it would integrate with Catesta.

Could you provide some examples or a sample project that illustrates how you'd like the Classes folder to be structured and used? Specifically, what scaffolding would you expect Catesta to generate, and how would the build tasks interact with this folder?

**Comment by dsolodow** [comment]
So I see that Stucco has this in their template (https://github.com/devblackops/Stucco/commit/357f8b009ef8f4fea4f27186d0e442993f212564) but it looks like Classes is just another folder of ps1 files that get rolled into the .psm1 so as long as the classes are ignored by the Pester & Code Coverage, it may be unnecessary. 

It would be nice to have as a parameter just to have it keep things organized, but now that I know the classes can just go in private or public, that's the required bit.
